### ISSUE TITLE
Tune PID for Fetcher motor

### ISSUE THREAD

**Issue by robot256** [FTC7393/FtcRobotController#22]

**Comment by FalseMSP** [comment]
yes
need more tuning
(probably integral)
proportional has been tuned

**Comment by robot256** [comment]
Fetcher is pretty well tuned at velocity PIDF = (30, 1, 0, 0).  The reason it was getting stuck in auto is because the lever compensation code was not accounted for.

**Comment by robot256** [comment]
Frequently when homing the fetcher with the preset, it will chatter against the hard stop before settling down.

Need to pull some log files to investigate.

It might be because the integrator is wound up and it hits the limit switch multiple times. Or there could be an error in how the limit switch reset is occurring.

**Comment by robot256** [comment]
There is a lot of issues with integrator windup when going out and stopping.  We need to reduce the integral gain and raise the proportional.

**Comment by robot256** [comment]
My dudes, we might need to try using the "F" part of PIDF. That might make it jump start the motor early.

**Comment by robot256** [comment]
We found good numbers to use in teleop, with no integrator whatsoever.  We need to find better numbers for auto that don't have 25 counts of steady state error.
