### ISSUE TITLE
Drive Speed

### ISSUE THREAD

**Issue by jvandegriff** [FTC7393/FtcRobotController#26]
Want to try getting used to faster drive for MTI submission. For driver 1, change the fast mode (pressing down on the left joystick) to full speed (I think it's set to .8 right now), and the normal drive speed increased by .1 -Gianni

**Comment by icanc0** [comment]
Fast mode: 0.9 -> 1.0
Normal mode: 0.65 -> 0.75
Fixed with commit https://github.com/FTC7393/FtcRobotController/commit/9412fd6a36c3cb3a939da84e1fe2749606673663
