### ISSUE TITLE
Lift Safety Regions

### ISSUE THREAD

**Issue by electricPotatoChip** [FTC7393/FtcRobotController#28]
Due to new hardware changes so that the crossbeam and grabber can no longer collide, we can now remove the lift safety regions, which will hopefully speed things up and prevent problems in auto.
The lift can be fully down regardless of lever position basically.

**Comment by FalseMSP** [comment]
waiiit
really?
i am bouta make our auto 0.1% more efficient :D

edit: updated code, needs testing 2022-PowerPlay-LiftSafetyRemoval
