### ISSUE TITLE
Add option to score only on Medium Junction

### ISSUE THREAD

**Issue by robot256** [FTC7393/FtcRobotController#30]
Find the new scoring position.
Trajectory from starting to Medium Scoring Position.
Trajectory from Medium Scoring Position to each parking position.
Options op to select it.

**Comment by robot256** [comment]
Hopefully incorporate this into #24

**Comment by zbrachinara** [comment]
Whoops this is not complete yet

**Comment by robot256** [comment]
Have we tested that it drives on the alternative trajectory and uses a different lift height?

Do we need to make another lift preset for medium auto?
