### ISSUE TITLE
Dropper Limit Switch

### ISSUE THREAD

**Issue by electricPotatoChip** [FTC7393/FtcRobotController#39]
Dropper limit switch will be ready for use today (Mar20), so we can add it to the tele-op and auto
Tele-op so that when you press RB, it will collect (placer to store and dropper to collect) until the limit switch is pressed, then move back to the brace state and stop intaking.
Pressing RB again during this will cancel the action and return to brace

Adding it to the auto so that it collects until the switch is pressed would also be a good idea

**Comment by robot256** [comment]
What happens if the limit switch doesn't get pressed?  Does the dropper spin forever?

**Comment by robot256** [comment]
Duplicate #23
