### ISSUE TITLE
Organize Options Op Listing

### ISSUE THREAD

**Issue by robot256** [FTC7393/FtcRobotController#44]
Look at improving the User Experience of the options op for world's by organizing and renaming the options we have.

- [x] Remove options that aren't used anymore.
- [x] Make sure the options we use every match are all at the top.
- [x] Check if any tuning values are permanent enough to move to code instead of options.
- [x] Consider combining options that depend on each other, to save space and avoid user error. 
- [x] Example 1: change the "cones to score" and "cones to fetch" options into one "cones to score and fetch", with an enum for "S1_F0", "S1_F1", "S2_F1", etc.
- [x] Example 2: Consolidate the "doScoring", and future "medium goal" and "retreat to medium goal" options into one "Strategy" option ("PARKONLY, MEDIUM, HIGH, HIGH_RETREAT")
- [x] Make the option names actually describe what they do and/or the reason why the user would change them
- [x] Check that the ranges and increments for each numerical value are appropriate.

**Comment by TheDeveloper101** [comment]
might be able to convert some options into numbers - have to check.
