### ISSUE TITLE
Make Auto Init Telemetry show strategy options selected

### ISSUE THREAD

**Issue by robot256** [FTC7393/FtcRobotController#45]
Make sure Auto Op shows telemetry during init of all the options that are changed for each match, so the user can verify them.

**Comment by icanc0** [comment]
its also possible to use some characters to represent the field, with the position of our robot and side, then have words in the middle so we're not confused.

quick fix with 5de3c665

**Comment by robot256** [comment]
Nice text.  It needs to be in the while loop that monitors camera output (before drive.update()) so it doesn't get overwritten.

Also need to update it with the new option framework (conestofetch becomes dobonusfetch).

**Comment by icanc0** [comment]
moved the options logging into the loop with 58925a4b
