### ISSUE TITLE
Improve/fix fetcher lockout while lever on stack

### ISSUE THREAD

**Issue by robot256** [FTC7393/FtcRobotController#47]
Right now useOffset locks out fetcher commands, but there are a few issues:

1. It causes all commands during useOffset to be discarded, not just delayed.
2. It applies to raising from ground height, when there is no stack.
3. It only applies until horizontal, not until the cone is clear of the stack.
4. It doesn't care whether the grabber is open or closed.

We can fix all of these by adding a new flag in scorer, "pauseFetcher", and two new variables, "unpauseFetcherAngle" and "pausedFetcherCommand".
- [x] pauseFetcher(stackHeight) will set fetcherPaused to true, set pausedFetcherCommand to fetcher.extensionSetPoint, and unpauseFetcherAngle to the required STACK_X_CLEAR preset angle.
- [x] unpauseFetcher() will clear fetcherPaused, set fetcher.extensionSetPoint to pausedFetcherCommand, and set unpauseFetcherAngle to +pi.
- [x] pauseFetcher(stackHeight) should be called by leverToggleHome and leverGoHome when starting in a stack1,2,3,4 high and going inside IF the grabber is closed.  
- [x] unpauseFetcher() should be called by any other lever command.
- [x] In scorer.act, when lever servo position is greater than unpauseFetcherAngle, also call unpauseFetcher().
- [x] In controlFetcher, discard each command of fetcherPaused is true.
- [x] In fetcherGoToPreset and setFetcherPosition (NOT controlFetcher):
* IF fetcherPaused is false, send the new command straight to fetcher.
* IF fetcherPaused is true, AND the new command value is LESS than the current command value, then the new command should be stored in pausedFetcherCommand.

**Comment by robot256** [comment]
Question: should we also lock out the mecanum drive joysticks while fetcher is locked?

**Comment by robot256** [comment]
Implementing this ticket will prevent Auto from knocking over the stack during the giveUp(tm) sequence.

**Comment by TheDeveloper101** [comment]
i'll do this one as well

**Comment by robot256** [comment]
Looks ready to test!

**Comment by robot256** [comment]
Something is going on and it's not pausing like it should when the grabber is closed.  It's possible that it's only pausing when the grabber is open.

**Comment by robot256** [comment]
Okay, the offset is taking place very briefly and the fetcher is slow to respond, so it does almost nothing.  But at the same time, the Auto seems to be able to pick up cone #4 just fine?  So it might be doing its job.
