### ISSUE TITLE
Auto Score in Tele-Op

### ISSUE THREAD

**Issue by electricPotatoChip** [FTC7393/FtcRobotController#57]
I'll be doing some changes to the Scoring position to work better with a compact alignment device, so I'd like access to the Auto Score Position on Driver 1 for cycling purposes.

I believe most if not all of the D-Pad is free, so probably set it to Up on the D-Pad. Same logic as the regular score.
When held, it goes to Auto Score position. When released it returns to brace.

**Comment by icanc0** [comment]
So it's a preset that goes to the scoring position with a single button?
