### ISSUE TITLE
Log File In Auto

### ISSUE THREAD

**Issue by robot256** [FTC7393/FtcRobotController#58]
This is getting ridiculous, we need a log file in auto ASAP. Can someone please make the SparkyMecanumDrive.update() function we call in all the autoOp wait loops do a log file entry at the end of it?

Start by logging the Roadrunner X, Y, and heading measurements (state).

**Comment by robot256** [comment]
Autocomplete context informed me that Qualcomm has their own DataLogger class now.  It's very simple.  I prototyped an implementation.  See https://github.com/FTC7393/FtcRobotController/commit/7519214ea58c25d66234c1ce2c44a9e6759d10dd

A couple other things from that commit are useful too, like making `SparkyMecanumDrive drive` a member of the opmode so we don't have to pass it as arguments.

**Comment by robot256** [comment]
Then we need Roadrunner pose error, Lift (setpoint, encoder, limit switch), Fetcher (setpoint, encoder, limit switch, useOffset, pauseFetcher), Curent position for servos Placer, Dropper, Lever, Grabber, Dropper limit switch.

**Comment by TheDeveloper101** [comment]
currently working on adding logging everywhere

**Comment by TheDeveloper101** [comment]
finally finished omg
