### ISSUE TITLE
Park fails in some cases

### ISSUE THREAD

**Issue by robot256** [FTC7393/FtcRobotController#69]
Seems to be related to either when the fetcher gets stuck or when the drive wheels get stuck on the ground junction.

We need to have a better abort for the fetcher retraction, or just ignore it and run into the wall.

We need to adjust the parking trajectory to get off the ground junction first.

**Comment by robot256** [comment]
Has this ever happened again?  We can close this if it doesn't happen anymore.

**Comment by icanc0** [comment]
this seems not to happen again if it's not stuck on something, lets close it after #72 is implemented and tested.
