### ISSUE TITLE
Tune auto on all 4 sides

### ISSUE THREAD

**Issue by icanc0** [FTC7393/FtcRobotController#71]
the right-side auto does not work for both blue and red.

the left-side auto worked before we installed the guards, but it does not work anymore because its been pushed back by the ground junction.

**Comment by icanc0** [comment]
also see #70 and #69 for more info, it should be done together

**Comment by robot256** [comment]
Need to test each path/strategy individually.  

_**Check each box once you get three runs in a row with at least 3 cones and parking, then move on**_  It's very important that we have GOOD ENOUGH on each one and don't get sidetracked trying to make one of them perfect.

- [x] Right side High junction, zone 1
- [x] Right side High junction, zone 2
- [x] Right side High junction, zone 3
- [x] Right side High junction with waitForRoadrunner on, zone 1
- [x] Right side High junction with waitForRoadrunner on, zone 2
- [x] Right side High junction with waitForRoadrunner on, zone 3
- [ ] Right side Park only, zone 1
- [ ] Right side Park only, zone 2
- [ ] Right side Park only, zone 3
- [ ] Left side High junction, zone 1
- [ ] Left side High junction, zone 2
- [ ] Left side High junction, zone 3
- [ ] Left side High junction with waitForRoadrunner on, zone 1
- [ ] Left side High junction with waitForRoadrunner on, zone 2
- [ ] Left side High junction with waitForRoadrunner on, zone 3
- [ ] Left side Park only, zone 1
- [ ] Left side Park only, zone 2
- [ ] Left side Park only, zone 3
- [x] Right side Medium junction, zone 1
- [x] Right side Medium junction, zone 2
- [x] Right side Medium junction, zone 3
- [x] Left side Medium junction, zone 1
- [x] Left side Medium junction, zone 2
- [x] Left side Medium junction, zone 3
- [x] Right side Medium junction with waitForRoadrunner on, zone 1
- [x] Right side Medium junction with waitForRoadrunner on, zone 2
- [x] Right side Medium junction with waitForRoadrunner on, zone 3
- [ ] Left side Medium junction with waitForRoadrunner on, zone 1
- [ ] Left side Medium junction with waitForRoadrunner on, zone 2
- [ ] Left side Medium junction with waitForRoadrunner on, zone 3

**Comment by icanc0** [comment]
test these on one side, since the code are the same for each side
- [ ] no bonus fetch
- [ ] less than 5 cones (check this if we don't have that as an option)

test on all sides
- [ ] park only

**Comment by icanc0** [comment]
first priority is testing the left side medium

**Comment by robot256** [comment]
Don't forget "preload only" (score 1 / no bonus fetch)

**Comment by FalseMSP** [comment]
fr need to tune ground junction auto too!!

fr tho
season over
closing issue
