### ISSUE TITLE
Cone misses the junction if waiting for roadrunner

### ISSUE THREAD

**Issue by robot256** [FTC7393/FtcRobotController#73]
If waitForRoadrunner takes too long, the place extends to the scoring position before the junction is in thr right place. We need to have the placer wait in the brace statr until roadrunner is done.

So the new sequence would look like:

1. Placer to brace
2. Lift to scoring height
3. Wait for roadrunner
4. Placer to score
5. Wait for lift
6. Wait for placer isDone
7. Dropper release

**Comment by FalseMSP** [comment]
It's now fixed

**Comment by robot256** [comment]
> It's now fixed

I saw! Great job!
