### ISSUE TITLE
IllegalArgumentException in auto

### ISSUE THREAD

**Issue by TheDeveloper101** [FTC7393/FtcRobotController#74]
Got an exception with leverToStackHeight() in Scorer.kt - line 26

**Comment by FalseMSP** [comment]
[AutoRR-2023-04-14T183648.414.csv](https://github.com/FTC7393/FtcRobotController/files/11237539/AutoRR-2023-04-14T183648.414.csv)
log ^

**Comment by FalseMSP** [comment]
shouldn't have happened in the first place...
but fix has been done + more logging to make it easier to debug in the future
